"""crate items

Revision ID: a2ec7eb2c1c8
Revises: 402b2dfeb53e
Create Date: 2021-07-10 15:30:03.610385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2ec7eb2c1c8'
down_revision = '402b2dfeb53e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
