"""update items

Revision ID: f4a85d9800e4
Revises: 9fc2bb0d905c
Create Date: 2021-07-10 22:17:54.358559

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f4a85d9800e4'
down_revision = '9fc2bb0d905c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('items_ibfk_1', 'items', type_='foreignkey')
    op.drop_column('items', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('user_id', mysql.CHAR(length=32), nullable=True))
    op.create_foreign_key('items_ibfk_1', 'items', 'users', ['user_id'], ['uuid'])
    # ### end Alembic commands ###
